import type { Metadata } from "next";
import "@/styles/globals.css";

import localFont from 'next/font/local';


export const ttNorms = localFont({
  src: [
    {
      path: '../../public/fonts/TTNorms/TTNorms-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/TTNorms/TTNorms-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-tt-norms',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Manual Case Study",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ttNorms.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
