import type { Metadata } from "next";
import "@/styles/globals.css";
import { QuizProvider } from "@/context/quizContext";

export const metadata: Metadata = {
  title: "Manual Case Study",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QuizProvider>{children}</QuizProvider>
      </body>
    </html>
  );
}
